import { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import vazirFont from "@constants/localFonts";
import "../styles/globals.css";
import { Header } from "@components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};
type LayoutRootProps = {
  children: ReactNode;
};
export default function RootLayout({ children }: LayoutRootProps) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirFont.variable} ${geistSans.variable} ${roboto.variable} font-sans min-h-screen`}
      >
        <Header />
        <div className="container xl:max-w-screen-xl">{children}</div>
      </body>
    </html>
  );
}
